### ISSUE TITLE
"rosrun node_example pytalker.py" showing errors

### ISSUE THREAD

**Issue by zongyaojin** [tdenewiler/node_example#3]
Hi Thomas,

I'm trying to learn from your package, and I had a problem when running it. 

So, if I do `roslaunch node_example node_example.launch` there is no problem, the package runs perfectly. 

And if I run individual nodes after doing `roscore`, `rosrun node_example talker`, `rosrun node_example listener`, and `rosrun node_example pylistener.py` have no problem.

However, if I run `rosrun node_example pytalker.py`, I always get the following error msg:

> $ rosrun node_example pytalker.py
> Traceback (most recent call last):
>   File "/home/zongyao/zongyao_ws/ros_ws/src/node_example/src/pytalker.py", line 79, in <module>
>     NodeExample()
>   File "/home/zongyao/zongyao_ws/ros_ws/src/node_example/src/pytalker.py", line 25, in __init__
>     rospy.loginfo('rate = %f', rate)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
>     self._log(INFO, msg, args, **kwargs)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
>     self.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
>     self.callHandlers(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
>     hdlr.handle(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
>     self.emit(record)
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 176, in emit
>     record_message = _defaultFormatter.format(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
>     msg = msg % self.args
> TypeError: float argument required, not str

So I was wondering where did I do wrong and if you could help me out?

Thank you very much!

Sincerely,
Zongyao

**Comment by zongyaojin** [comment]
I think I forgot to pass in the parameters, `rosrun node_example pytalker.py _message:="Hello world!" _a:=57 _b:=-15 _rate:=1` solved the problem. Sorry for the stupid mistake :sweat_smile:

**Comment by tdenewiler** [comment]
@zongyaojin The crash you observed was a legitimate bug. Thanks for reporting the issue. I fixed it in pull request #4 . If you have other questions/issues please open a new issue and I will help as best I can.

FYI, when running from a launch file or passing in parameters on the command line we were overwriting the type of the variable from string to float. When using the previous default value the type was a string. I tried to then print it and use it as a float and that is what was causing the crash you observed.

**Comment by zongyaojin** [comment]
@tdenewiler Thank you for your reply, that was really helpful. I noticed something else you might want to change, and submitted a pull request. Please take a look if you're interested. 

I tested the changes I made in the PR on my local machine (Ubuntu 16.04, Kinetic), they worked.

But the PR didn't pass the Travis CI build test, with error 
> The command "sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116" failed and exited with 2 during .

I've never worked with Travis CI, so I don't know why that happened.

Again, thank you!
