### ISSUE TITLE
Code coverage is not working

### ISSUE THREAD

**Issue by Axel13fr** [tdenewiler/node_example#34]
Hi,

I tried to reproduce your example but the travis console log shows that the code coverage is now working: "Error: No coverage report found". The command returns 0 so the build passes but the coverage actually doesn't work.

Do you have any ideas ?

**Comment by tdenewiler** [comment]
I've found codecov to be finicky. I'm assuming this is for https://github.com/Axel13fr/lib_sonarcov, so I'll take a look at it.

**Comment by Axel13fr** [comment]
I've managed to modify my travis file based on your recipe and I'm now using the following, taken from their codecov examples.
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' 'unit_tests/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info # debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

In the console I can see some proper coverage info (https://travis-ci.org/github/Axel13fr/lib_sonarcov/jobs/675727185#L2427) but codecov.io still ends up in an error so I will probably ask them :-)

**Comment by tdenewiler** [comment]
Asking codecov is probably a good idea, and I'd be interested in following that conversation. I'll keep investigating too.

One thing I noticed is that you should not need a `CODECOV_TOKEN` since you are working with a public repository via Travis. See https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-upload-token.

**Comment by tdenewiler** [comment]
One more thing I noticed is that the last build to upload from Travis to Codecov was

https://travis-ci.org/github/tdenewiler/node_example/builds/646601236

However, the latest commit to master did not find any reports and is not shown at Codecov.

https://travis-ci.org/github/tdenewiler/node_example/builds/667350530

The only difference I see is that the build that worked used Codecov v2.0.15, and the build that did not work used Codecov v2.0.22. There are a fair amount of differences between the versions but nothing jumps out at me as a problem.

https://github.com/codecov/codecov-python/compare/v2.0.15...v2.0.22

**Comment by tdenewiler** [comment]
For what it's worth, I am slowly migrating all my repositories from Travis to Github Actions. I don't have it working for ROS-based repositories yet.

**Comment by tdenewiler** [comment]
There were 2 main issues that I found:

1. `PYTHONPATH` was being configured to force specific paths with Python 2.7.
1. `codecov` must be run from the directory containing the package. I don't know why that is the case.

A pull request was provided to address those issues at Axel13fr/lib_sonarcov#1.

If you have any more problems please let me know and I'll try to help.

**Comment by Axel13fr** [comment]
Just in case something interesting comes out, I've tried to get more infos from codecov via:
https://community.codecov.io/t/code-coverage-report-failure/1287/2
and
https://github.com/codecov/codecov-python/issues/249

Last but not least, I think your travis file is better than the one I had started with https://github.com/felixduvallet/ros-travis-integration/blob/master/.travis.ymlin that it uses catkin tools instead of catkin_make. Do you want to PR that or did you try already but it was rejected ?

**Comment by tdenewiler** [comment]
I based my Travis config file off the one you link to. I like catkin tools better, and I like your pattern of building on kinetic and melodic in parallel better. I'm fine if you want to push my changes to a PR in the upstream repo, I never tried.

Note that yesterday I did get this repo switched from Travis to Github Actions for continuous integration. Codecov is working just fine with Actions.
