### ISSUE TITLE
When should I use ros::init to initialize a node

### ISSUE THREAD

**Issue by Yaru-Gu** [tdenewiler/node_example#49]
Hi,
I'm a new comer to ROS and trying to use the _node_example_ package to get some basic ideas about ros nodes. I'm confused about when to use ros::init to initialize a ros node, as I couldn't find the initialization process in talker.cpp and listener.cpp. Although the nodes _talker_ and _listener_ have been initialized in _talker_node.cpp_ and _listener_node.cpp_ respectively, these two cpp files have not been launched by any launch files. It would be appreciated if anyone could help me with this misunderstanding. It has confused me for several days.
Also, should the node name in the function _ros::init(argc, argv, "my_node_name")_ be the same as the name of the executable file which defines the node?

**Comment by tdenewiler** [comment]
There are 2 questions here. I'll answer the first now.

In `CMakeLists.txt` the files `talker.cpp` _and_ `talker_node.cpp` are used to create the executable `talker`. It is a similar setup for the `listener` executable.

https://github.com/tdenewiler/node_example/blob/main/CMakeLists.txt#L26

All files in the `include` directory (such as `talker.h`) are also available.

https://github.com/tdenewiler/node_example/blob/main/CMakeLists.txt#L24

When generating the `talker` executable the compiler knows to use information contained in `talker.cpp` and `talker_node.cpp` and `talker.h` to make sure all functions are available and being called correctly and all classes are initialized correctly.

ROS nodes are the executables generated when running `catkin build` inside the workspace. Typically, you can find them at locations such as `devel/lib/node_example/talker`. After building the workspace and sourcing it, that location is on your `PATH` so the executables are able to be found and run.

Launch files start executables that have been compiled (or copied/symlinked in the case of Python files), where the executable to run is specified by the `type` field in the `node` tag. For example, here is where the `talker` node/executable is started in a launch file.

https://github.com/tdenewiler/node_example/blob/main/launch/c%2B%2B_node_example.launch#L10

Hope that helps.

**Comment by Yaru-Gu** [comment]
Hi Thomas,
Thank you so much. Everything is much clear to me now. I'll go ahead and close the topic. Thanks again.

**Comment by tdenewiler** [comment]
For your second question about the string used when calling `ros::init`. The string you provide will be the name of the node when you use `ros run`. That name is overwritten by the `name` field of the `node` tag when you use `ros launch`. The string used when calling `ros::init` is not required to match the node/executable name from `CMakeLists.txt` but I almost always see it match.
